#!/bin/sh
# Wrapper around clang-format to make enforcing new oblong coding style easy

# Abort on error
set -e

# Avoid bashisms
POSIXLY_CORRECT=1

# Running operating system
OS=$(uname -s)

abort() {
  echo "error: $*"
  exit 1
}

print_help_menu() {
  cat <<_EOF_
Spruce: Don't Let Messes Overstay Their Welcome
Handy-dandy oblong-specific C++ code beautifier
See https://gitlab.oblong.com/platform/docs/wikis/coding-style/

usage: spruce [-o outdir] file...         (reformat given files)
or:    spruce [-o outdir] all             (reformat all files)
or:    spruce -                           (reformat stdin to stdout)
or:    spruce changes                     (reformat all edits, staged and unstaged)
or:    spruce check [files...]            (list files that need reformatting)
or:    spruce precommit                   (abort if a staged file needs reformatting)
or:    spruce freebase <sha1_before_reformat> <sha1_after_reformat> <upstream_branch>
or:    spruce plugin (emacs|vim|sublime)  (custom plugin support)
or:    spruce style                       (output our .clang-format to stdout)

'freebase' is for fixing a branch that is stale because upstream was spruced up
after the branch was created.

'plugin' has options for emacs, vim or sublime:
    'sublime': produces a file, 'clang_format_custom.sublime-settings' which
               should be used with the plugin: https://packagecontrol.io/packages/Clang%20Format
_EOF_
  if $IN_ERR
  then
    exit 1
  fi
  exit 0
}

# Expected version of clang-format
# note: Must match debian/control
#CLANG_FORMAT_VERSION_DESC="(tags/google/stable/2016-12-09)"
#CLANG_FORMAT_SHORT_VERSION="4.0.0"
#CLANG_FORMAT_BREW_PKG="clang-format"
CLANG_FORMAT_VERSION_DESC="(tags/RELEASE_380/final)"
CLANG_FORMAT_SHORT_VERSION="3.8"
CLANG_FORMAT_BREW_PKG="clang-format38"

# Name of clang-format as a binary
CLANG_FORMAT_PROGNAME="clang-format"
CLANG_FORMAT_PKGNAME="clang-format"
GIT_CLANG_FORMAT_PROGNAME="git-clang-format"

if [ "$OS" = "Linux" ] ; then
  GIT_CLANG_FORMAT_PROGNAME="$GIT_CLANG_FORMAT_PROGNAME-$CLANG_FORMAT_SHORT_VERSION"
  CLANG_FORMAT_PROGNAME="$CLANG_FORMAT_PROGNAME-$CLANG_FORMAT_SHORT_VERSION"
  CLANG_FORMAT_PKGNAME="$CLANG_FORMAT_PROGNAME"
elif [ "$OS" = "Darwin" ] ; then
  CLANG_FORMAT_PKGNAME="$CLANG_FORMAT_BREW_PKG"
fi

# Yovo paths to ignore when formatting
IGNORE_PATHS=' |gtest'
IGNORE_PATHS="$IGNORE_PATHS|valgrind"
IGNORE_PATHS="$IGNORE_PATHS|ob-hash.c|ob-hash-city.c|ob-hash-win32.c"
IGNORE_PATHS="$IGNORE_PATHS|ob-mvtypes.c"
IGNORE_PATHS="$IGNORE_PATHS|dSFMT.c|dSFMT.h"
IGNORE_PATHS="$IGNORE_PATHS|test-hash.c"
IGNORE_PATHS="$IGNORE_PATHS|benchmarks/city"
IGNORE_PATHS="$IGNORE_PATHS|openssl_hostname_validations"

# Helpers to take our format string where it needs to go

# Pick a place for the file, and remove it when we exit
CLANG_FORMAT_STYLE_FILE=/tmp/spruce.clang-format.$$
cleanup_style() {
    rm -f "$CLANG_FORMAT_STYLE_FILE"
}
trap cleanup_style 0

# Get style suitable for users to put in ~/.clang-format if they wish
cat_style_file() {
   cat $CLANG_FORMAT_STYLE_FILE
}

# Get style suitable for -style=, but less legible
cat_style_string() {
   tr '\012' ',' < $CLANG_FORMAT_STYLE_FILE | sed 's/^/{/;s/,$/}/'
}

# Our format is embedded in this script in alphabetical order.
# We turn this into a single line by joining with commas, so
#  - maps are a bit funny
#  - we can't use comments inside this style, so put 'em here

#--- style comments follow ---
# AlwaysBreakBeforeMultilineStrings: false # true forces line breaks after OB_FMT_64
# BraceWrapping:
#  AfterEnum: 'true'                       # Broken: https://bugs.llvm.org/show_bug.cgi?id=27381
#--- end of style comments ---
# And finally, our style:
cat > "$CLANG_FORMAT_STYLE_FILE" <<_EOF_
Language: Cpp
AccessModifierOffset: -1
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlinesLeft: false
AlignOperands: true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: true
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
AlwaysBreakTemplateDeclarations: true
BinPackArguments: true
BinPackParameters: true
BraceWrapping: {AfterClass: true
  AfterControlStatement: true
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: false
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  BeforeCatch: true
  BeforeElse: true
  IndentBraces: true}
BreakBeforeBinaryOperators: All
BreakBeforeBraces: Custom
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
ColumnLimit: 80
CommentPragmas: ''
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat: false
ExperimentalAutoDetectBinPacking: false
ForEachMacros:   [ foreach, Q_FOREACH, BOOST_FOREACH ]
IndentCaseLabels: true
IndentWidth: 2
IndentWrappedFunctionNames: false
KeepEmptyLinesAtTheStartOfBlocks: true
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 3
NamespaceIndentation: None
PointerAlignment: Right
ReflowComments: false
SortIncludes: false
SpaceAfterCStyleCast: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeParens: Always
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 2
SpacesInAngles: false
SpacesInContainerLiterals: true
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: Cpp11
TabWidth: 2
UseTab: Never
_EOF_


OUTPUT_PATH=""
IN_ERR=false

case "$1" in
""|-h|--help)
    print_help_menu
    ;;
-o)
    shift
    OUTPUT_PATH=$1
    shift
    ;;
-) ;;
-*)
    echo "Invalid option: $1" >&2
    IN_ERR=true
    print_help_menu
    ;;
esac

update_brew() {
  b=$(which brew)
  if [ "$b" = "" ] ; then
    msg="ERROR: brew: command not found. Shall I install it for you (y/n)?"
    printf %s "$msg "
    read -r ans
    INVALID=true
    while $INVALID ; do
      case "$ans" in
        y|Y|yes)
          INVALID=false
          ;;
        n|N|no)
          abort "Failed to run clang-format"
          ;;
        * )
          echo  "Invalid Answer. Please answer [y/n]: "
          read -r ans
          ;;
      esac
    done

    echo "Installing brew..."
    brew_url="https://raw.githubusercontent.com/Homebrew/install/master/install"
    /usr/bin/ruby -e "$(curl -fsSL $brew_url)"

    b=$(which brew)
    if [ "$b" = " " ] ; then
      abort "Failed to install brew"
    fi
  fi

  echo "Updating brew..."
  brew update
}

unlink_clang_format() {
  if [ "$OS" = "Darwin" ] ; then
    for p in $(brew list | grep clang-format)
    do
      brew unlink "$p"
    done
  fi
}

install_clang_format() {
  echo "installing clang-format..."
  if [ "$OS" = "Darwin" ] ; then
    brew tap Homebrew/homebrew-versions
    brew install $CLANG_FORMAT_PKGNAME
    brew link --force $CLANG_FORMAT_PKGNAME
  elif [ "$OS" = "Linux" ] ; then
    sudo apt-get install $CLANG_FORMAT_PKGNAME
  fi
}

test_clang_format_version() {
  clang_v=$($CLANG_FORMAT_PROGNAME --version || true)
  case "$clang_v" in
  *"$CLANG_FORMAT_VERSION_DESC"*) return;;
  esac

  if [ "$clang_v" = "" ] ; then
    msg="ERROR: clang-format: command not found. Shall I install it for you (y/n)?"
  else
    echo "ERROR: clang-format: wrong version ($clang_v)"
    msg="Shall I install $CLANG_FORMAT_SHORT_VERSION for you (y/n)?"
    if [ "$OS" = "Darwin" ] ; then
      msg="$msg (WARNING: Answering yes will unlink your current version)"
    fi
  fi

  printf %s "$msg "
  read -r ans
  INVALID=true
  while $INVALID ; do
    case "$ans" in
      y|Y|yes)
        INVALID=false
        ;;
      n|N|no)
        abort "Failed to run clang-format"
        ;;
      * )
        printf %s "Invalid Answer. Please answer [y/n]: "
        read -r ans
        ;;
    esac
  done

  if [ "$OS" = "Darwin" ] ; then
    update_brew
    if [ "$clang_v" != "" ] ; then
      unlink_clang_format
    fi
  elif [ "$OS" = "Linux" ] ; then
    sudo apt-get update
  fi

  install_clang_format
  clang_v=$($CLANG_FORMAT_PROGNAME --version)

  case "$clang_v" in
  *"$CLANG_FORMAT_VERSION_DESC"*)
    echo "Using Clang Version: $clang_v"
    ;;
  *)
    abort "Wanted clang-format version $CLANG_FORMAT_VERSION_DESC, got $clang_v.  Aborting."
    ;;
  esac
}

# Logic borrowed from mongodb:
# https://github.com/mongodb/mongo/blob/master/buildscripts/clang_format.py#L727
reformat_branch() {
  echo "reformat a branch made before a clang-format run..."

  pre=$1
  post=$2
  master=$3

  val="$(git rev-parse --show-toplevel)"
  if [ "$(pwd)" != "$val" ] ; then
    abort "ERROR: Branch reformatting must be done from the repo root: $val"
  fi

  # if not os.path.exists("buildscripts/clang_format.py"):
  #     raise ValueError("reformat-branch is only supported in the mongo repo")

  # Validate that user passes valid commits
  if ! git cat-file -e "$pre" > /dev/null 2>&1
  then
    abort "ERROR: Commit prior to reformat $pre is not a valid commit in this repo"
  fi
  if ! git cat-file -e "$post" > /dev/null 2>&1
  then
    abort "ERROR: Commit after reformat $post is not a valid commit in this repo\n"
  fi

  if ! git merge-base --is-ancestor "$pre" "$post" > /dev/null 2>&1
  then
    abort "ERROR: Commit Prior to Reformat $pre is not a valid ancestor of Commit After Reformat $post in this repo"
  fi

  # Validate the user is on a local branch that has the right merge base
  if ! git symbolic-ref --quiet HEAD > /dev/null 2>&1
  then
    abort "ERROR: You must not run this script in a detached HEAD state"
  fi

  # Validate the user has no pending changes
  if ! git diff --quiet
  then
    abort "ERROR: Your working tree has pending changes. You must have a clean working tree before proceeding."
  fi

  val=$(git merge-base HEAD "$pre") > /dev/null 2>&1
  if [ "$val" != "$pre" ] ; then
    abort "ERROR: Please rebase to $pre and resolve all conflicts before running this script"
  fi

  val=$(git merge-base HEAD "$master") > /dev/null 2>&1
  if [ "$val" != "$pre" ] ; then
    abort "ERROR: This branch appears to already have advanced too far through the merge process"
  fi

  # Everything looks good so lets start going through all the commits
  val=$(git rev-parse --abbrev-ref HEAD) > /dev/null 2>&1
  if [ "$val" = "HEAD" ] ; then
    abort "Branch is currently detached"
  fi
  new_branch="$val-reformatted"

  if git rev-parse --verify "$new_branch" > /dev/null 2>&1
  then
    abort "The branch $new_branch already exists. Please delete or rename the current branch."
  fi

  commits=$(git log --reverse --pretty=format:%H "$pre"..HEAD) > /dev/null 2>&1

  previous_commit_base=$post

  # # Go through all the commits the user made on the local branch and migrate to a new branch
  # # that is based on post_reformat commits instead
  for c in $commits
  do
    echo "${c}:"
    git checkout --quiet "$c" > /dev/null 2>&1

    deleted_files=""
    # Format each of the files by checking out just a single commit from the user's branch
    commit_files=$(git diff --name-only HEAD~) > /dev/null 2>&1
    for commit_file in $commit_files
    do
      # Format each file needed if it was not deleted
      if [ ! -e "$commit_file" ] ; then
        echo "Skipping file $commit_file since it has been deleted in commit '$c'"
        deleted_files="${deleted_files}$commit_file:"
        continue
      fi

      if ! is_formattable_file "$commit_file" ; then
        echo "Skipping file $commit_file since it is not a file clang_format should format"
      else
        $CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" -i "$commit_file"
        echo "format $commit_file"
      fi
    done

    # Check if anything needed reformatting, and if so amend the commit
    if git diff --quiet > /dev/null 2>&1
    then
      echo "Commit $c needed no reformatting"
    else
      git commit --all --amend --no-edit > /dev/null 2>&1
    fi

    # Rebase our new commit on top the post-reformat commit
    prev_commit=$(git rev-parse HEAD) > /dev/null 2>&1

    # Checkout the new branch with the reformatted commits
    # Note: we will not name as a branch until we are done with all commits on the local branch
    git checkout --quiet "$previous_commit_base" > /dev/null 2>&1

    # Copy each file from the reformatted commit on top of the post reformat
    for diff_file in $(git diff --name-only "$prev_commit"~.."$prev_commit")
    do
      # If the file was deleted in the commit we are reformatting, we need to delete it again
      case "$deleted_files" in
      *"$diff_file"*)::
        git rm "$diff_file" > /dev/null 2>&1
        continue
        ;;
      esac

      # The file has been added or modified, continue as normal
      root_dir=$(dirname "$diff_file")
      if [ ! -e "$root_dir" ] ; then
        mkdir -p "$root_dir"
      fi
      git show "$prev_commit":"$diff_file" > "$diff_file"

      git add "$diff_file" > /dev/null 2>&1
    done

    # Create a new commit onto clang-formatted branch
    git commit --reuse-message="$prev_commit" > /dev/null 2>&1

    previous_commit_base=$(git rev-parse HEAD)
  done

  # Create a new branch to mark the hashes we have been using
  git checkout -b "$new_branch" > /dev/null 2>&1

  cat <<_EOF_
-----------------------------------------
NOTICE:
reformat-branch is done running.
A copy of your branch has been made named $new_branch, and formatted with clang-format.
The original branch has been left unchanged.
The next step is to rebase the new branch on 'iz'.
_EOF_
}

test_clang_format_version

preprocess_stdin() {
  # Work around https://llvm.org/bugs/show_bug.cgi?id=30849, part 1
  # Convert our wrappers back into something recognizable
  perl -p \
    -e 's,OB_PRIVATE:,private:/*SPRUCE*/,;' \
    -e 's,OB_PROTECTED:,protected:/*SPRUCE*/,;' \
    -e 's,OB_PUBLIC:,public:/*SPRUCE*/,;' \
  #
}

postprocess_stdin() {
  # Work around https://llvm.org/bugs/show_bug.cgi?id=30849, part 2
  # Bring back our wrappers
  perl -p \
    -e 's,private: */\*SPRUCE\*/,OB_PRIVATE:,;' \
    -e 's,protected: */\*SPRUCE\*/,OB_PROTECTED:,;' \
    -e 's,public: */\*SPRUCE\*/,OB_PUBLIC:,;' \
  #
}

# Return true if the argument looks like the name of a C/C++/objC file.
# (Note: this is one of several filtering methods in this script.
# format_changes, precommit, and check without args use their own ways of
# selecting files.  This one is used if user specifies
# filenames directly on commandline; it accepts more types than
# format_changes and precommit do.)
is_formattable_file() {
    case "$1" in
    *.[cChHm])            ;; # .c .C .h .H .m
    *.[cChH][+pPx][+pPx]) ;; # .cpp .CPP .c++ .cxx .hpp .HPP etc.
    *.mm)                 ;; # objective-C++
    *)
        return 1             # false
        ;;
    esac
    return 0                 # true
}

format_files() {
  for f
  do
    echo "$f"
    if ! is_formattable_file "$f"
    then
        echo "Skipping $f (filename doesn't look like c/c++/objc)"
        continue
    fi
    preprocess_stdin < "$f" \
    | $CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" \
    | postprocess_stdin > spruce-tmp.tmp
    outf="$f"
    if [ "$OUTPUT_PATH" != "" ] ; then
      outf="$OUTPUT_PATH/$f"
      mkdir -p "$(dirname "$outf")"
    fi
    mv spruce-tmp.tmp "$outf"
  done
}

# Format all staged .C/.c/.h/.cpp files, even if they're in the IGNORE_PATHS
# FIXME: stop using git-clang-format so we can skip files in IGNORE_PATHS
format_changes() {
#  $GIT_CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" -f --extensions c,cpp,h
  for outf in $(git status | awk '/modified:/ {print $2}' | grep -E -wv "$IGNORE_PATHS" )
  do
    echo "$outf"
    if ! is_formattable_file "$outf"
    then
        echo "Skipping $outf (filename doesn't look like c/c++/objc)"
        continue
    fi
    preprocess_stdin < "$outf" > spruce-tmp.tmp && mv spruce-tmp.tmp "$outf"
    $CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" -i "$outf"
    postprocess_stdin < "$outf" > spruce-tmp.tmp && mv spruce-tmp.tmp "$outf"
  done
}

sublime_wants_containers_on_single_line() {
  perl -e 'while (<STDIN>) {
            if (/:( +)"[[{]/) { $merge=1; };
            if ($merge) {
              s/"(\w+)"/'\''$1'\''/g;
              s/\n$//;
              if (/[]}]/) { $merge=0;  s/$/\n/; };
            };
            print;
          }'
}

generate_sublime() {
  echo "{"

  # in the order of the lines below:
  #   1. Put all keys/vals (words) in double quotes (i.e k: v -> "k": "v")
  #   2. Put quotes around array blocks (i.e. [] -> "[]")
  #   3. Add a comma at the end of every line
  #   4/5. Put quotes around map blocks (i.e. {} -> "{}")
  #   6. For every array/map block, remove new lines and replace double quotes with singles
  #   7/8. Path fallout from #6 which changes the initial key to single quotes (bad)
  #   9. Skip empty strings
  perl -p \
    -e 's/(([A-Za-z]+[0-9_-]*)+)/"$1"/g;' \
    -e 's/(\[.*])/"$1"/g;' \
    -e 's/\n/,\n/g;' \
    -e 's/{/"{/g;' \
    -e 's/}/}"/g;' \
  | sublime_wants_containers_on_single_line \
  | perl -p \
      -e 's/'\''BraceWrapping'\''/"BraceWrapping"/g;' \
      -e 's/'\''ForEachMacros'\''/"ForEachMacros"/g;' \
  | grep -v "''" \
  #

  echo "}"
}

generate_emacs() {
  cat > "spruce-emacs.el" <<_EOF_
;; This file is a minimal spruce emacs-integration. To install:
;; - Make sure spruce is installed and on your path.
;; - Add to your .emacs:
;;
;;   (load "<path-to-this-file>/spruce-emacs.el")
;;   (global-set-key (kbd "C-M-<tab>") 'spruce-current-file)
;;
;; The second line sets the key binding for running the sprucification. Change
;; "C-M-<tab>" to another binding if you need spruce on a different key
;; (C-M-<tab> stands for Ctrl+Meta+Tab).
;;
;; With this integration you can press the bound key and spruce will save your
;; current buffer and then run spruce against it.
;;
;; To revert a formatting, just undo.

(defun spruce-current-file ()
  "spruce the current file and revert the buffer"
  (interactive)
  (let ((spruce (locate-file "spruce" exec-path)))
    (if (not spruce)
        (error "Spruce not found, can't spruce"))
    (let* ((spruce-command (concat spruce " "
                                   (shell-quote-argument (buffer-file-name))))
           (buff (current-buffer))
           (buff-cmp (lambda () (if (eq (current-buffer) buff) t nil))))
      (save-some-buffers nil 'buff-cmp)
      (shell-command spruce-command))
    (revert-buffer t t t)))
_EOF_
}

generate_vim() {
  cat > "spruce-vim.py" <<_EOF_
# This file is a minimal spruce vim-integration. To install:
# - Change 'binary' if spruce is not on the path (see below).
# - Add to your .vimrc:
#
#   map <C-I> :pyf <path-to-this-file>/spruce-vim.py<cr>
#   imap <C-I> <c-o>:pyf <path-to-this-file>/spruce-vim.py<cr>
#
# The first line enables clang-format for NORMAL and VISUAL mode, the second
# line adds support for INSERT mode. Change "C-I" to another binding if you
# need spruce on a different key (C-I stands for Ctrl+i).
#
# With this integration you can press the bound key and spruce will save your
# current buffer and then run spruce against it.
#
# To revert a formatting, just undo.

import subprocess
import vim

# set g:spruce to the path to spruce if it is not on the path
# Change this to the full path if spruce is not on the path.
binary = 'spruce'
if vim.eval('exists("g:spruce_path")') == "1":
  binary = vim.eval('g:spruce_path')

def main():
  # Get the current file path.
  file = vim.eval('expand("%:p")')

  # Save the current buffer before running
  vim.command('write')

  # Avoid flashing an ugly, ugly cmd prompt on Windows when invoking spruce.
  startupinfo = None
  if sys.platform.startswith('win32'):
    startupinfo = subprocess.STARTUPINFO()
    startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    startupinfo.wShowWindow = subprocess.SW_HIDE

  # Call spruce.
  command = [binary, file]
  p = subprocess.Popen(command,
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                       stdin=subprocess.PIPE, startupinfo=startupinfo)
  stdout, stderr = p.communicate()

  # If successful, replace buffer contents.
  if stderr:
    print stderr

  # reload buffer
  vim.command('edit')

main()
_EOF_
}

deploy_plugin() {
  case "$1" in
    emacs)
      generate_emacs
      cat <<_EOF_
spruce-emacs.el has been created in the current working directory

To use:
  1. Copy the file to its final resting place (your choice)
  2. Follow the instructions in the comments at the top of the file

_EOF_
      ;;
    vim)
      generate_vim
      cat <<_EOF_
spruce-vim.py has been created in the current working directory

To use:
  1. Copy the file to its final resting place (your choice)
  2. Follow the instructions in the comments at the top of the file

_EOF_
      ;;
    sublime)
      cat_style_file | generate_sublime > clang_format_custom.sublime-settings
      cat <<_EOF_
clang_format_custom.sublime-settings has been created in the current working directory

To use:
  1. Copy the file to:
     Mac OS X: '~/Library/Application\ Support/Sublime Text 3/Packages/SublimeClangFormat'
     Linux: '~/.config/sublime-text-3/Packages/SublimeClangFormat'
  2. In Sublime:
     1. Tools -> Command Palette -> Select "Clang-Format: Select Style" -> Select "Custom"
     2. Highlight code and type super+option+a on OSX and ctrl+option+a otherwise
  See https://github.com/rosshemsley/SublimeClangFormat for more
_EOF_
      ;;
    *)
      cat <<_EOF_
ERROR: plugin takes an argument to specify the IDE.
Options are: 'emacs', 'vim', or 'sublime'
You provided: '$1'

_EOF_
      print_help_menu
      exit 1
      ;;
  esac
}

# Print pretty error message to stderr so it doesn't interfere with the list
# of files, in case someone wants to redirect it to a file.
print_error_header() {
  cat >&2 <<"_EOF_"
 _____________
< Style Error >
 -------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Please use spruce to reformat your code.
See https://gitlab.oblong.com/platform/docs/wikis/coding-style

Offending file(s):
_EOF_
}

# Run style check on given files without changing them
# Abort loudly on style error
# Exit silently on success
check_files() {
  failed=false
  for f
  do
    if ! is_formattable_file "$f"
    then
        echo "Skipping $f (filename doesn't look like c/c++/objc)"
        continue
    fi
    # Look for replacements with nonzero length
    # (We could format and diff, but this is marginally faster?)
    if preprocess_stdin < "$f" \
       | $CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" -output-replacements-xml \
       | tee /tmp/spruce.tmp \
       | grep "<replacement .* length='[^0].*'>" > /dev/null
    then
      if ! "$failed"
      then
        failed=true
        print_error_header
      fi
      echo "$f"
    fi
  done
  if "$failed"
  then
    exit 1
  fi
}

case "$1" in
  style)
    cat_style_file
    ;;
  plugin)
    # Provide plugin support for given IDE
    if [ $# -ne 2 ] ; then
      cat <<_EOF_
ERROR: plugin takes an argument to specify the IDE.
Options are: 'emacs', 'vim', or 'sublime'

_EOF_
      IN_ERR=true
      print_help_menu
    fi
    deploy_plugin "$2"
    ;;
  all)
    # format all .C/.c/.h/.cpp files that are not in the IGNORE_PATHS
    # shellcheck disable=SC2046
    format_files $(find . -type f -iname '*.[ch]' -o -iname '*.cpp' | grep -E -wv "$IGNORE_PATHS")
    ;;
  changes)
    format_changes
    ;;
  precommit)
    # Check all staged .C/.c/.h/.cpp files that are not in the IGNORE_PATHS
    # shellcheck disable=SC2046
    check_files $(git diff --name-only HEAD --diff-filter=AM | grep -E -i '\.[ch]$|\.cpp$' | grep -E -wv "$IGNORE_PATHS")
    ;;
  check)
    shift
    # Check given .C/.c/.h/.cpp files (default: all that are not in the IGNORE_PATHS)
    if test "$*" = ""
    then
        # shellcheck disable=SC2046
        check_files $(find . -type f -iname '*.[ch]' -o -iname '*.cpp' | sed 's,^\./,,' | grep -E -wv "$IGNORE_PATHS")
    else
        check_files "$@"
    fi
    ;;
  freebase)
    shift
    # Fix a branch whose upstream has since been reformatted
    if [ $# -ne 3 ] ; then
      cat <<_EOF_
ERROR: freebase takes 3 args: sha1_before_reformat sha1_after_reformat upstream_branch
but you provided: $@

_EOF_
      IN_ERR=true
      print_help_menu
    fi
    reformat_branch "$1" "$2" "$3"
    ;;
  -)
    # If 1st arg is -, format stdin and send result to stdout.
    preprocess_stdin | $CLANG_FORMAT_PROGNAME -style="$(cat_style_string)" | postprocess_stdin
    ;;
  *)
    if ! test -f "$1"
    then
        echo "ERROR: $1 is not a file or command?"
        echo ""
        print_help_menu
        exit 1
    fi
    # shellcheck disable=SC2046,SC2012,SC2010
    format_files $(ls -d "$@" | grep -E -wv "$IGNORE_PATHS")
    ;;
esac
